- background.js
> Brand blocked image

- background.js
> Resize image while drawing. Much, much faster.

- background.js
> Adding missing \/ detection

- background.js
- dns_blocking.js
- manifest.json
- options.html
- options.js
> Cloudflare for families

- background.js
See #70 . This fixes the vast majority of test cases, but number 9 still fails.
> Detect charset

- background.js
- manifest.json
- processor.html
- processor.js
Potential fix for the Firefox 83 performance issue #75 . Moves all processing to a hidden extension page.
> Processing using an extension page

- background.js
- manifest.json
- whitelist.js
> Basic reCAPTCHA whitelist carveout

- processor.js
> Throttling to 1, similar performance

- background.js
> Removing extra check that would throw off stats

- processor.js
Unfortunately I don't have a clear reproduction scenario for this one and even after stressing/hammering on this for quite a while I haven't been able to reproduce it. The watchdog logic for the happy path seems to work well enough. I'll just have to keep monitoring this.
> Adding a watchdog. Haven't been able to get it to kick yet but normal behavior is stable

- background.js
- background_video.js
- manifest.json
- processor.js
- status.js
Well, it's not perfect yet. But provides a minimalist progress bar in the bottom left and video busy/block indicator in the bottom right.
> Status indicator breakout

- background.js
- processor.js
Fixes #104 . Note that the B64/Video do not get the same treatment; I generally have not seen the same level of issues with them.
> Adding stuck image check watchdog

- background.js
- options.html
- options.js
- processor.js
Allows user to select backend from options. Note the secondary processor doesn't actually get any work assigned to it yet.
> Choose backend

- background.js
- options.html
- options.js
> Video blocking exposed in options

- silent_credits.js
> Replacing insertAdjacentHtml usage to avoid warning in AMO submission

- background.js
> Fix for when the whole return of charset is undefined

- background.js
- manifest.json
- processor.js
> Watchdog for crash detection and automatic plugin reload

- background_video.js
- manifest.json
- mp4.js
- Generic DASH MP4 support (e.g. many Reddit videos)
- Filters out audio-only MP4's
> Generic DASH support for MP4

- background.js
- processor.html
Potential fix for #150. I want to let this settle for a while.
> Hardening crash detection and processing page closing

- background.js
For the originally reported URL (https://www.nokia.com/phones/de_at/support/api/pdf/nokia-5310-user-guide), the following logs/header/response was observed:
CHARSET: No Content-Type header detected for https://www.nokia.com/phones/de_at/support/api/pdf/nokia-5310-user-guide, adding one. background.js:655:28
CHARSET: Detected base type was text/html
HTTP/2 200 OK
server: nginx/1.23.1
x-frame-options: SAMEORIGIN
content-language: de-AT
content-disposition: inline; filename="user-guide-nokia-5310-user-guide.pdf"
x-varnish: 59445958
accept-ranges: bytes
date: Thu, 05 Jan 2023 05:44:28 GMT
content-length: 261166
set-cookie: nok_ip_locale=US; expires=Sat, 04-Feb-2023 05:44:28 GMT; path=/; secure; HttpOnly
set-cookie: nok_ip_region=americas; path=/; secure; HttpOnly
strict-transport-security: …
> #182: For PDF guess at Content-Type when none is supplied by probing Conent-Disposition filename

- background.js
> Making meta tag utf-8 detection more flexible based on real world feedback

- background.js
Note that this is still less than ideal.
I looked into the matter further and it appears that essentially you're supposed to default to the encoding based on the locale. In this case it is en so it should be iso-8859-1.  However, even in the bug report it appears that LinkedIn usually defaults to utf-8 even though I don't see any of the usual markers to indicate it should switch. Not doing so eventually leads to a 0x92 getting misencoded if present on the page.
It seems like this has perhaps changed over the years. For example, consider test 4 here: https://www.w3.org/2006/11/mwbp-tests/test-encoding-4.html This seems to indicate that utf-8 _might_ be the default, but interestingly the test "fails" with vanilla Firefox and Chrome. However, Wingman Jr. "passes" it - but perhaps when it …
> Add fallback to utf-8 when character encoding is unspecified and iso-8859-1 encoding fails on a chunk

- processor.js
Fix cleanup of failed base64 filtering requests
> Fix B64 error cleanup handler
